name: Pack

on:
  push:
    branches: [ "main" ] 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm ci

      - name: Pack project
        run: npm pack

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: git-synchronizer
          path: '*.tgz'